const dartGameData = [
    {   
        player1Name: 'Pekka',
        player2Name: 'Jukka',  
        player1Score: 3,
        player2Score: 2,
        player1Average: 85.5,
        player2Average: 78.2,
        player1HighestFinish: 10,
        player2HighestFinish: 0,
        player1BestLeg: 9,
        player2BestLeg: 35,
        player1HighestScore: 180,
        player2HighestScore: 48,
      },
    {   
        player1Name: 'Pekka',
        player2Name: 'Jukka',  
        player1Score: 3,
        player2Score: 1,
        player1Average: 95.5,
        player2Average: 74.1,
        player1HighestFinish: 12,
        player2HighestFinish: 0,
        player1BestLeg: 9,
        player2BestLeg: 35,
        player1HighestScore: 180,
        player2HighestScore: 48,
      },
    {   
        player1Name: 'Pekka',
        player2Name: 'Jukka',  
        player1Score: 3,
        player2Score: 2,
        player1Average: 85.5,
        player2Average: 78.2,
        player1HighestFinish: 120,
        player2HighestFinish: 0,
        player1BestLeg: 9,
        player2BestLeg: 35,
        player1HighestScore: 180,
        player2HighestScore: 48,
      },
    {   
        player1Name: 'Pekka',
        player2Name: 'Jukka',  
        player1Score: 3,
        player2Score: 2,
        player1Average: 85,
        player2Average: 12.2,
        player1HighestFinish: 10,
        player2HighestFinish: 0,
        player1BestLeg: 9,
        player2BestLeg: 35,
        player1HighestScore: 180,
        player2HighestScore: 48,
      },
    {   
        player1Name: 'Pekka',
        player2Name: 'Jukka',  
        player1Score: 3,
        player2Score: 2,
        player1Average: 85.5,
        player2Average: 78.2,
        player1HighestFinish: 50,
        player2HighestFinish: 0,
        player1BestLeg: 9,
        player2BestLeg: 35,
        player1HighestScore: 180,
        player2HighestScore: 48,
      },
  ];
  
  export default dartGameData;